### ISSUE TITLE
Please re-introduce Maven or another build system that works in common IDEs

### ISSUE THREAD

**Issue by nordfalk** [Sciss/SyntaxPane#14]
Can't run the project from Netbeans

I have no idea about Scala, I just installed ALL the Scala plugins I could.

Whatever I do,
 - Source code is not visible

 - I can build thru this SBT thing, but Test doesent work.

 - When I choose 'Run' if fails:

SBT -Completion: <tab> -Exit: exit -Help: help. 
sbt-launch=/usr/local/netbeans-8.0/nbscala/modules/ext/org.netbeans.libs.sbt/1/org-scala-sbt/sbt-launch.jar
[info] Loading project definition from /home/j/esperanto/apertium/SyntaxPane/project
[info] Set current project to SyntaxPane (in build file:/home/j/esperanto/apertium/SyntaxPane/)
> run
[info] Running de.sciss.syntaxpane.SyntaxTester 
[error] Error: Could not find or load main class de.sciss.syntaxpane.SyntaxTester
java.lang.RuntimeException: Nonzero exit code returned from runner: 1
	at scala.sys.package$.error(package.scala:27)
[trace] Stack trace suppressed: run last compile:run for the full output.
[error] (compile:run) Nonzero exit code returned from runner: 1
[error] Total time: 1 s, completed 01-05-2015 11:49:50

Finally I managed to get the demo up by typing "test:run"

In general, I'm impressed with how hard it is to get this project up and running for a non-Scala user.

Would it be hard for you to re-introduce Maven or another build system that just works in most common IDEs, for those of us who doesent use Scala?

**Comment by Sciss** [comment]
No, I'm sorry, when I left Java I was very happy to leave Ant and Maven behind. The `README.md` explicitly says the demo is in the test scope: `sbt test:run`, so it cannot get easier than that I'm afraid. Also you should not need to install _any_ Scala "plug-ins" (whatever that is), not even Scala itself. sbt will take care of this, that's why it's such a great build tool. On [http://sbt.github.io/] you are one click away from a simple installation on any platform.
